"""Parameterized mode — fit a trace's envelope, then sample the grid around it.

Replay answers "what happens under this exact traffic". Parameterized mode
answers "what happens across the region this traffic lives in, **and beyond it**"
— which is the question a playbook row has to survive, because the customer's
next hour is never the trace's next hour.

The traces define the realistic envelope; the sampler covers the envelope plus
margin, and every point outside it is labelled ``in_envelope=False`` and carries
``/xenv`` in its regime label. An extrapolation that cannot be told apart from a
measurement is worse than no extrapolation.

Distributions are fitted **empirically** — a 101-point quantile grid, sampled by
inverse-CDF interpolation. No parametric family is assumed: production length
distributions are multi-modal (short chat turns and long document prompts in one
trace) and a lognormal fit would smear the modes together and quietly change the
prefill/decode ratio the whole exercise turns on.

Arrival burstiness is generated by drawing **per-bin counts from a negative
binomial**, whose index of dispersion is ``1 + m/r`` and so can be set directly
to the target. A Poisson process is the ``D = 1`` special case and is used as
such. ``D < 1`` (more regular than Poisson — a paced or rate-limited client) is
clamped to Poisson and noted; ponytail: a binomial thinning would cover it, add
it when a real trace shows underdispersion.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Iterator

import numpy as np
from pydantic import BaseModel, ConfigDict, Field

from gitm.traffic.regime import DEFAULT_BIN_S, Regime, SourceKind, index_of_dispersion
from gitm.traffic.schema import CanonicalRequest, Trace, TraceMeta

#: Quantile grid used for both length distributions. 101 points keeps the tails
#: (p99, p100) as real samples rather than as an extrapolated fit.
_QUANTILES = np.linspace(0.0, 100.0, 101)


class RegimeFit(BaseModel):
    """One trace's envelope, as the axes the sampler moves along."""

    model_config = ConfigDict(extra="forbid")

    trace: str  # source identity the fit came from
    source_sha256: str  # the bytes it was fitted on
    requests: int
    span_s: float
    rate_rps: float
    burstiness: float
    bin_s: float = DEFAULT_BIN_S
    input_quantiles: list[float] = Field(default_factory=list)
    output_quantiles: list[float] = Field(default_factory=list)

    def sample_lengths(self, rng: np.random.Generator, n: int, *, output: bool) -> np.ndarray:
        """Inverse-CDF draw from the fitted empirical distribution."""
        q = np.asarray(self.output_quantiles if output else self.input_quantiles)
        u = rng.uniform(0.0, 100.0, size=n)
        return np.interp(u, _QUANTILES, q)


def fit(trace: Trace, *, bin_s: float = DEFAULT_BIN_S) -> RegimeFit:
    """Fit the regime axes of a real trace."""
    if len(trace) < 2:
        raise ValueError("need at least two requests to fit an envelope")
    outs = trace.output_tokens
    if not outs:
        raise ValueError("cannot fit output lengths: the trace carries none")
    return RegimeFit(
        trace=trace.meta.source,
        source_sha256=trace.meta.sha256,
        requests=len(trace),
        span_s=trace.meta.span_s,
        rate_rps=trace.rate_rps(),
        burstiness=index_of_dispersion(
            trace.arrivals, bin_s=bin_s, span_s=trace.meta.span_s
        ),
        bin_s=bin_s,
        input_quantiles=[float(x) for x in np.percentile(trace.input_tokens, _QUANTILES)],
        output_quantiles=[float(x) for x in np.percentile(outs, _QUANTILES)],
    )


def _arrivals(
    rng: np.random.Generator, *, rate_rps: float, burstiness: float, duration_s: float, bin_s: float
) -> np.ndarray:
    """Arrival times with a controlled index of dispersion."""
    nbins = max(int(np.ceil(duration_s / bin_s)), 1)
    m = rate_rps * bin_s
    if m <= 0:
        return np.zeros(0)
    if burstiness <= 1.0:
        counts = rng.poisson(m, size=nbins)
    else:
        var = burstiness * m
        p = m / var  # NB with mean m, variance var
        r = m * p / (1.0 - p)
        counts = rng.negative_binomial(r, p, size=nbins)
    starts = np.repeat(np.arange(nbins) * bin_s, counts)
    return np.sort(starts + rng.uniform(0.0, bin_s, size=starts.size))


def sample_trace(
    fit_: RegimeFit,
    *,
    rate_mult: float = 1.0,
    burstiness: float | None = None,
    input_scale: float = 1.0,
    output_scale: float = 1.0,
    duration_s: float | None = None,
    seed: int = 0,
) -> tuple[Trace, Regime]:
    """Draw one synthetic trace from the fitted envelope, plus its regime tag.

    Returns the trace and its :class:`~gitm.traffic.regime.Regime`. The regime's
    ``in_envelope`` is False whenever any axis is pushed past what the source
    trace actually showed — the margin the brief asks for, labelled as margin.
    """
    burstiness = fit_.burstiness if burstiness is None else burstiness
    duration_s = fit_.span_s if duration_s is None else duration_s
    rate = fit_.rate_rps * rate_mult
    rng = np.random.default_rng(seed)

    arrivals = _arrivals(
        rng, rate_rps=rate, burstiness=burstiness, duration_s=duration_s, bin_s=fit_.bin_s
    )
    n = arrivals.size
    if n == 0:
        raise ValueError("sampled zero requests — raise rate_mult or duration_s")
    inp = np.maximum(np.rint(fit_.sample_lengths(rng, n, output=False) * input_scale), 1)
    out = np.maximum(np.rint(fit_.sample_lengths(rng, n, output=True) * output_scale), 1)

    params = {
        "fit": fit_.trace,
        "source_sha256": fit_.source_sha256,
        "rate_mult": rate_mult,
        "burstiness": burstiness,
        "input_scale": input_scale,
        "output_scale": output_scale,
        "duration_s": duration_s,
        "bin_s": fit_.bin_s,
        "seed": seed,
    }
    # A synthetic trace has no bytes on disk, so its identity is the digest of the
    # parameters that reproduce it exactly. Same digest, same trace.
    digest = hashlib.sha256(json.dumps(params, sort_keys=True).encode()).hexdigest()

    requests = [
        CanonicalRequest(arrival_s=float(a), input_tokens=int(i), output_tokens=int(o))
        for a, i, o in zip(arrivals, inp, out, strict=True)
    ]
    tol = 1e-9
    in_envelope = (
        rate_mult <= 1.0 + tol
        and burstiness <= fit_.burstiness + tol
        and input_scale <= 1.0 + tol
        and output_scale <= 1.0 + tol
    )
    notes = [f"sampled from {fit_.trace} envelope", json.dumps(params, sort_keys=True)]
    if burstiness < 1.0:
        notes.append("burstiness < 1 requested; clamped to a Poisson process")
    meta = TraceMeta(
        source="parameterized",
        path=f"synthetic:{digest[:16]}",
        sha256=digest,
        rows_read=n,
        rows_emitted=n,
        span_s=float(arrivals[-1] - arrivals[0]) if n > 1 else 0.0,
        raw_time_unit="s",
        notes=notes,
    )
    trace = Trace(meta=meta, requests=requests)
    regime = Regime.from_trace(
        trace,
        source_kind=SourceKind.SYNTHETIC,
        bin_s=fit_.bin_s,
        in_envelope=in_envelope,
        trace_id=f"{fit_.trace}~{digest[:8]}",
    )
    return trace, regime


#: Default grid. Deliberately asymmetric: the interesting margin is *above* the
#: observed trace (more load, burstier, longer outputs), because that is where a
#: playbook row gets applied and nobody measured.
DEFAULT_RATE_MULTS = (0.5, 1.0, 2.0, 4.0)
DEFAULT_BURST_TARGETS = (1.0, 4.0, 16.0)
DEFAULT_OUTPUT_SCALES = (1.0, 2.0)


def grid(
    fit_: RegimeFit,
    *,
    rate_mults: tuple[float, ...] = DEFAULT_RATE_MULTS,
    burst_targets: tuple[float, ...] = DEFAULT_BURST_TARGETS,
    output_scales: tuple[float, ...] = DEFAULT_OUTPUT_SCALES,
    duration_s: float | None = None,
    seed: int = 0,
) -> Iterator[tuple[Trace, Regime]]:
    """Sample the whole grid. One seed per cell, derived, so cells are independent
    but the sweep as a whole is reproducible from ``seed`` alone."""
    for i, rm in enumerate(rate_mults):
        for j, b in enumerate(burst_targets):
            for k, os_ in enumerate(output_scales):
                yield sample_trace(
                    fit_,
                    rate_mult=rm,
                    burstiness=b,
                    output_scale=os_,
                    duration_s=duration_s,
                    seed=seed + 1000 * i + 100 * j + 10 * k,
                )
